flat_teaching.Rmd:
  path: dev/flat_teaching.Rmd
  state: active
  R: R/add_one.R
  tests: tests/testthat/test-add_one.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_teaching.Rmd
    vignette_name: Get started
    open_vignette: false
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
