# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Add one to any value
#'
#' @param value A numeric value
#'
#' @return Numeric. value + 1
#' @export
#' @examples
#' add_one(12)
#' add_one(56)

add_one <- function(value) {
  result <- value + 1
  return(result)
}
